# WARNING: Don't forget to update environment_docker.yml as well!
name: pdal_ign_plugin
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.12.*
  - numpy
  - conda-forge:pdal==2.8.*
  - conda-forge:python-pdal>=3.4
  - gdal
  - geopandas
# --------- dev dep --------- #
  - cmake
  - pre-commit # hooks for applying linters on commit
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  - pytest
  - twine
# --------- pip & pip libraries --------- #
  - pip
  - pip:
    - build # Installed via pip after issues when creating the environment ("build does not exist")
    # Install laspy with laszip laz compression (as laszip is an implementation of the laz 1.4 standard)
    - laspy[laszip]  # Installed via pip because laszip is not handled by the conda package.
    - ign-pdal-tools==1.7.8
