name: pdal_ign_plugin
channels:
  - conda-forge
  - anaconda
dependencies:
  - pdal
  - python-pdal
  - gdal
  - cmake
  - pip
  - pip:
    - ign-pdal-tools
# --------- dev dep --------- #
  - pre-commit # hooks for applying linters on commit
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  - pytest


