name: pdal_ign_plugin
channels:
  - conda-forge
  - anaconda
dependencies:
  - pdal
  - python-pdal
  - pytest
  - black
  - isort
  - shapely
  - gdal
  - cmake
  - pip
  - pip:
    - ign-pdal-tools


