name: pdal_ign_plugin
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.12.*
  - numpy
  - conda-forge:pdal>=2.9.*
  - conda-forge:python-pdal>=3.4
  - gdal
  - geopandas
# --------- dev dep --------- #
  - pytest
# --------- pip & pip libraries --------- #
  - pip
  - pip:
    - ign-pdal-tools==1.15.0
    - laspy[lazrs]


