name: pdal_ign_plugin
channels:
  - conda-forge
  - anaconda
dependencies:
  - pdal
  - geopandas
  - laspy
  - python-pdal
  - gdal
# --------- dev dep --------- #
  - cmake
  - pre-commit # hooks for applying linters on commit
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  - pytest
  - build
  - twine
# --------- pip & pip libraries --------- #
  - pip
  - pip:
    - ign-pdal-tools==1.7.7
