name: pdal_ign_plugin
channels:
  - conda-forge
  - anaconda
dependencies:
  - pdal
  - python-pdal
  - gdal
  - pytest
  # --------- pip & pip libraries --------- #
  - pip
  - pip:
    - ign-pdal-tools
