name: cicd_deploy

on:
  # For now, run each time some code are push on main
  push:
    branches:
      - main

env:
  DOCKER_REPO: ignimagelidar/pdal_ign_plugin

jobs:

  build_and_deploy_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: install cppunit
      run: sudo apt install -y libcppunit-dev

    - name: compil
      run: ./build.sh

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and export to Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: ${{ env.DOCKER_REPO }}:test

    - name: Run tests in docker
      run: >
        docker run
        --ipc=host
        ${{ env.DOCKER_REPO }}:test
        python -m pytest -m docker -s --log-cli-level DEBUG

    - name: Set version number
      run: |
        echo "VERSION=$(python -m test.version)" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REPO }}:latest,${{ env.DOCKER_REPO }}:${{ env.VERSION }}
