name: cicd_test

on:
  # Run each time some code are push on any branch
  push:
    branches:
      - '**'
    paths-ignore:
      - 'doc/**'

jobs:

  build_and_run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: install cppunit
      run: sudo apt install -y libcppunit-dev

    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: pdal_ign_plugin
        environment-file: ./environment.yml
        auto-activate-base: true
    
    - name: compil_plugins
      run: source ./ci/build.sh

    - name: test
      run: source ./ci/launch_test.sh
