name: cicd_docker

on:
  # Run tests for non-draft pull request on main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: pdal_ign_plugin

jobs:

  build_docker_image_and_run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Build docker image
      run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:test .

    - name: Run tests in docker image
      run: docker run ${{ env.DOCKER_IMAGE_NAME }}:test python -m pytest

