name: cicd_test

on:
  # Run each time some code is pushed on any branch
  push:
    branches:
      - '**'
    paths-ignore:
      - 'doc/**'

jobs:

  build_and_run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: install cppunit
      run: sudo apt install -y libcppunit-dev

    # See https://github.com/marketplace/actions/setup-micromamba
    - name: setup-micromamba
      uses: mamba-org/setup-micromamba@v2.0.4
      with:
        environment-file: environment.yml
        environment-name: pdal_ign_plugin  # activate the environment
        cache-environment: false
        cache-downloads: true
        generate-run-shell: true
        shell: bash

    - name: compile_plugins
      shell: micromamba-shell {0}
      run: |
       mkdir -p build
       cd build
       cmake -G"Unix Makefiles" -DCONDA_PREFIX=$MAMBA_ROOT_PREFIX -DCMAKE_BUILD_TYPE=Release ../
       make install

    - name: run tests
      shell: micromamba-shell {0}
      run: |
        export PDAL_DRIVER_PATH=./install/lib
        echo $PDAL_DRIVER_PATH
        python -m pytest -s
