name: cicd_docker

on:
  # Run tests for non-draft pull request on main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: pdal_ign_plugin
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build_docker_image_and_run_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Build docker image
      run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:test .

    - name: Run tests in docker image
      run: docker run ${{ env.DOCKER_IMAGE_NAME }}:test python -m pytest

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
