name: Check Quality
on: [pull_request]


jobs:
  tests-python:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2 # A personaliser selon langage de développement
      with:
        python-version: 3.8 #Spécifier votre version de dev ou version latest si vous voulez vous en abstraire
    - name : Checkout librairie-commune #
      uses: actions/checkout@v3
      with:
        repository: "ignf-sidc/librairie-commune"
        ref: "dev"
        path: python_lib/librairie-commune
        ssh-key: ${{ secrets.RSA_GITHUB_WORKFLOW }}
    - name: Install dependencies of librairie-commune
      run: pip install -r python_lib/librairie-commune/install/requirements.txt
    - name: Install dependencies
      run: pip install -r install/requirements.txt
    - name: "Analyse code with black" 
      run: black --diff --check bin
    - name: "Analyse code with pylint"
      run: pylint --rcfile=.pylintrc --disable=fixme bin --recursive=y
    - name: "Analyse code with mypy"
      run: mypy --strict bin
    - name: "Run unit tests"
      run: python3 -m unittest discover -b -s ignf_bag.tests.unit -p *TestCase.py
      working-directory: bin
